@host = 127.0.0.1
@port = 3443
@baseUri = https://{{host}}:{{port}}
@gqlUri = {{baseUri}}/graphql
@contentType = application/json
@requestType = GraphQL

@userLoginUsername = admin
@userLoginPassword = 12345678
@userIdAdmin = efeed3eb-c0a2-4b3e-816f-2a42ca8451b3
@userIdJohnDoe = 520c2eb5-e83b-4ef5-a343-85756bcce149
@userLoginJohnDoe = johndoe
@authToken = {{userLogin.response.body.$.data.userLogin.accessToken}}

### mutation: userLogin
// @name userLogin
POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}

mutation userLogin($loginUserData: LoginUserInput!) {
	userLogin(loginUserData: $loginUserData) {
		accessToken
		user {
			id
			username
			email
			roles
		}
	}
}

{
	"loginUserData": {
		"username": "{{userLoginUsername}}",
		"password": "{{userLoginPassword}}"
	}
}

### mutation: userLogout
// @name userLogout
POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

mutation userLogout {
	userLogout
}

### authRefreshToken
// @name authRefreshToken
// when refresh token always sent new authTokens
// authToken and refreshToken (cookie)
// it will fail after we logout or increase version with authRevokeRefreshToken, 
// the version of inMemory doesn't match the version of refresh token
// requires configure cookie middleware in AuthModules `configure(consumer: MiddlewareConsumer)`

POST {{baseUri}}/refresh-token HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### mutation: revokeUserRefreshTokens
// @name revokeUserRefreshTokens
POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

mutation revokeUserRefreshTokens($username: String!) {
	revokeUserRefreshTokens(username: $username)
}

{
	"username": "{{userLoginUsername}}"
}

### mutation: userProfile
// @name userProfile
POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

query userProfile{
  userProfile {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
	}
}

### query: users
// @name users

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

query users{
  users{
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

### query: userById
// @name userById

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

query userById($id: String!) {
  userById(id: $id) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"id": "{{userIdAdmin}}"
}

### query: userByUsername
// @name userByUsername

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

query userByUsername($username: String!) {
  userByUsername(username: $username) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"username": "{{userLoginJohnDoe}}"
}

### query: userRegister
// @name userRegister

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
X-REQUEST-TYPE: {{requestType}}
Authorization: Bearer {{authToken}}

mutation userRegister($newUserData: NewUserInput!){
  userRegister(newUserData: $newUserData) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"newUserData": {
		"username": "koakh",
		"password": "12345678",
		"firstName": "Mário",
		"lastName": "Monteiro",
		"email": "mail@koakh.com",
		"metaData": { 
			"key": "new user registered"
		}
	}
}	

### mutations update: userUpdate

// @name userUpdate
// neo4j: MATCH (n:User {id:"4ea88521-031b-4279-9165-9c10e1839002"}) RETURN n.roles, n.metaDataInternal

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
X-REQUEST-TYPE: {{requestType}}

mutation userUpdate($updateUserData: UpdateUserInput!) {
  userUpdate(updateUserData: $updateUserData) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"updateUserData": {
		"id": "{{userIdJohnDoe}}",
		"email": "another@koakh.com",
		"metaData": {
			"key": "valueUpdatedAgain"
		}
	}
}

### mutations update: userUpdatePassword

// @name userUpdatePassword
// neo4j:

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
X-REQUEST-TYPE: {{requestType}}

mutation userUpdatePassword($updateUserPasswordData: UpdateUserPasswordInput!) {
  userUpdatePassword(updateUserPasswordData: $updateUserPasswordData) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"updateUserPasswordData": {
		"id": "{{userIdAdmin}}",
		"password": "87654321"
	}
}

### mutations update: userUpdateProfile

// @name userUpdateProfile
// neo4j:  MATCH (n:User {id:"b2756e4d-0b69-49cd-a446-64c884e01f9e"}) RETURN n.id,n.email,n.mobilePhone,n.postal,n.city,n.region,n.geoLocation,n.timezone,n.useralInfo,n.metaData

POST {{gqlUri}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
X-REQUEST-TYPE: {{requestType}}

mutation userUpdateProfile($updateUserProfileData: UpdateUserProfileInput!) {
  userUpdateProfile(updateUserProfileData: $updateUserProfileData) {
    id
    username
    firstName
    lastName
    email
    roles
    createdDate
    metaData
  }
}

{
	"updateUserProfileData": {
		"email": "profileupdated@example.com",
		"metaData": {
			"key": "metaDataUpdated on profile"
		}
	}
}

### subscriptions to be used in graphql playground

subscription userLogged{
  userLogged
}

subscription userAdded {
  userAdded {
    id
  }
}

subscription userUpdated {
  userUpdated {
    id
  }
}

subscription userPasswordUpdated {
  userPasswordUpdated {
    id
  }
}

subscription userProfileUpdated {
  userProfileUpdated {
    id
  }
}
