version: '3.6'

services:
  koakh-nestjs-graphql-starter:
    container_name: koakh-nestjs-graphql-starter
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./config:/usr/src/app/config
      # hack to prevent the node_modules existing in the container to ever be overridden.
      - /usr/src/app/node_modules
    ports:
      - ${HTTPS_SERVER_PORT}:${HTTPS_SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    # command: npm run start:prod
    env_file:
      - .env
