version: '3.3'

services:

  solidarychain-frontend-react-playground:
    container_name: solidarychain-frontend-react-playground
    # used as tag
    image: solidarychain/solidarychain-frontend-react-playground
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - '1337:80'
    # environment:
      # - VAR=value
