version: '3.7'

services:

  koakh-nestjs-graphql-starter:
    container_name: koakh-nestjs-graphql-starter
    image: koakh-nestjs-graphql-starter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
