version: '3.3'

services:

  solidarychain-frontend-react-playground:
    image: solidarychain/solidarychain-frontend-react-playground
    container_name: solidarychain-frontend-react-playground
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - '3000:80'
