version: '3.7'

services:

  solidarychain-frontend-playground-dev:
    container_name: solidarychain-frontend-playground-dev
    image: solidarychain-frontend-playground-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
